---
modules-search: [ local ]

instances:

sequence:
- show:
  - welcome
  - locale
  - keyboard
  - partition
  - users
- exec:
  - partition
  - mount
  - unpackfs
  - machineid
  - fstab
  - locale
  - keyboard
  - localecfg
  - initcpiocfg
  - initcpio
  - users
  - displaymanager
  - networkcfg
  - hwclock
  - services
  - grubcfg
  - bootloader
  - preservefiles
  - umount
- show:
  - finished

branding: amitos
prompt-install: true
dont-chroot: false
oem-setup: false
disable-cancel: false
disable-cancel-during-exec: false
hide-back-and-next-during-exec: false
quit-at-end: false
